<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoice['invoice_number'] }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #0f172a; font-size: 12px; }
        h1 { font-size: 22px; margin: 0 0 4px; }
        .muted { color: #475569; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th, td { border-bottom: 1px solid #e2e8f0; padding: 8px 4px; text-align: left; }
        th { font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; color: #334155; }
        .right { text-align: right; }
        .totals { margin-top: 12px; width: 240px; margin-left: auto; }
        .notice { margin-top: 24px; font-size: 10px; color: #64748b; }
    </style>
</head>
<body>
    <h1>Invoice</h1>
    <p class="muted">{{ $invoice['invoice_number'] }}</p>
    <table>
        <tr>
            <td>
                <strong>{{ $invoice['business_name'] }}</strong><br>
                {{ $invoice['business_email'] ?? '' }}<br>
                {!! nl2br(e($invoice['business_address'] ?? '')) !!}
            </td>
            <td class="right">
                Issued {{ $invoice['issue_date'] }}<br>
                Due {{ $invoice['due_date'] }}<br>
                Currency {{ $calculated['currency'] }}
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <strong>Bill to</strong><br>
                {{ $invoice['customer_name'] }}<br>
                {{ $invoice['customer_email'] ?? '' }}<br>
                {!! nl2br(e($invoice['customer_address'] ?? '')) !!}
            </td>
        </tr>
    </table>
    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th class="right">Qty</th>
                <th class="right">Unit price</th>
                <th class="right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($calculated['items'] as $item)
                <tr>
                    <td>{{ $item['description'] }}</td>
                    <td class="right">{{ $item['quantity'] }}</td>
                    <td class="right">{{ $item['unit_price'] }}</td>
                    <td class="right">{{ $item['line_total'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <table class="totals">
        <tr><td>Subtotal</td><td class="right">{{ $calculated['subtotal'] }}</td></tr>
        <tr><td>Tax ({{ $calculated['tax_rate'] }}%)</td><td class="right">{{ $calculated['tax'] }}</td></tr>
        <tr><td><strong>Total</strong></td><td class="right"><strong>{{ $calculated['total'] }}</strong></td></tr>
    </table>
    @if (! empty($invoice['notes']))
        <p><strong>Notes</strong><br>{!! nl2br(e($invoice['notes'])) !!}</p>
    @endif
    @if (! empty($invoice['payment_instructions']))
        <p><strong>Payment instructions</strong><br>{!! nl2br(e($invoice['payment_instructions'])) !!}</p>
    @endif
    <p class="notice">This document was generated by QuickSolve. It does not collect payment and it is not a guarantee of tax compliance. Check the figures before you send them.</p>
</body>
</html>
